using System.Collections.Generic;
using System.Linq;
using NUnit.Framework;
using UnityEngine;

namespace BiomeRivals.Demo.Tests
{
    /// <summary>
    /// Validates the vanilla entity geometry pipeline: JSON parsing (modern and
    /// legacy formats), box-UV mesh construction, bone hierarchy and
    /// auto-fitting, plus integration over every locally extracted model.
    /// </summary>
    public sealed class DemoMinecraftEntityModelTests
    {
        // Independent physical-corner correspondence from pinned Blockbench box UV,
        // after reflecting source X into Unity. Numeric fixture is deliberately not
        // generated by the production UV-layout helper (64x32 atlas, 2x3x4 cube).
        private static Vector2[] ReferenceBoxCorners(int face, bool mirror)
        {
            var regions = new[] { new Vector4(11,13,9,10), new Vector4(17,13,15,10),
                new Vector4(15,13,11,10), new Vector4(9,13,5,10),
                new Vector4(11,10,9,6), new Vector4(13,6,11,10) };
            var region = regions[mirror && face == 2 ? 3 : mirror && face == 3 ? 2 : face];
            if (mirror) (region.x, region.z) = (region.z, region.x);
            return new[] { new Vector2(region.x,region.y), new Vector2(region.x,region.w),
                new Vector2(region.z,region.w), new Vector2(region.z,region.y) };
        }

        private static GameObject BuildBoxFixture(bool mirror, Material material)
        {
            var json = "{\"format_version\":\"1.8.0\",\"geometry.box\":{\"texturewidth\":64,\"textureheight\":32,\"bones\":[{\"name\":\"body\",\"pivot\":[0,0,0],\"cubes\":[{\"origin\":[-1,-1.5,-2],\"size\":[2,3,4],\"uv\":[5,6],\"mirror\":" + (mirror ? "true" : "false") + "}]}]}}";
            var root = new GameObject("SixFaceBox");
            Assert.That(DemoMinecraftEntityModelBuilder.TryBuild(root.transform,
                DemoMinecraftEntityGeometryParser.Parse(json, "geometry.box"),
                new DemoMinecraftEntityModelBuilder.BuildOptions { PrimaryTextureKey = "test", TextureWidth = 64,
                    TextureHeight = 32, MaterialProvider = _ => material }), Is.True);
            return root;
        }

        [TestCase(0,false)] [TestCase(1,false)] [TestCase(2,false)]
        [TestCase(3,false)] [TestCase(4,false)] [TestCase(5,false)]
        [TestCase(0,true)] [TestCase(1,true)] [TestCase(2,true)]
        [TestCase(3,true)] [TestCase(4,true)] [TestCase(5,true)]
        public void BoxUvMatchesIndependentPhysicalCorners(int face, bool mirror)
        {
            var material = new Material(Shader.Find("Standard"));
            var root = BuildBoxFixture(mirror, material);
            try
            {
                var uv = root.GetComponentInChildren<MeshFilter>().sharedMesh.uv;
                var expected = ReferenceBoxCorners(face, mirror);
                for (var corner = 0; corner < 4; corner++)
                    Assert.That(Vector2.Distance(uv[face * 4 + corner],
                        new Vector2(expected[corner].x / 64f, 1f - expected[corner].y / 32f)),
                        Is.LessThan(0.000001f), "face/corner " + face + "/" + corner);
            }
            finally { Object.DestroyImmediate(root); Object.DestroyImmediate(material); }
        }

        [TestCase(0,false)] [TestCase(1,false)] [TestCase(2,false)]
        [TestCase(3,false)] [TestCase(4,false)] [TestCase(5,false)]
        [TestCase(0,true)] [TestCase(1,true)] [TestCase(2,true)]
        [TestCase(3,true)] [TestCase(4,true)] [TestCase(5,true)]
        public void BoxUvSixFacesRenderAsymmetricAtlasThroughEntityShader(int face, bool mirror)
        {
            var texture = new Texture2D(64,32,TextureFormat.RGBA32,false,true)
                { filterMode = FilterMode.Point, wrapMode = TextureWrapMode.Clamp };
            for (var y = 0; y < 32; y++) for (var x = 0; x < 64; x++)
                texture.SetPixel(x,31-y,new Color((x+.5f)/64f,(y+.5f)/32f,.4f,1));
            texture.Apply();
            var material = new Material(Shader.Find("BiomeRivals/Demo/Entity")) { mainTexture = texture };
            var root = BuildBoxFixture(mirror, material);
            var cameraObject = new GameObject("SixFaceCamera");
            var target = new RenderTexture(128,128,24,RenderTextureFormat.ARGB32,RenderTextureReadWrite.Linear);
            var readback = new Texture2D(128,128,TextureFormat.RGBA32,false,true);
            var previous = RenderTexture.active;
            var fog = RenderSettings.fog;
            try
            {
                foreach (var transform in root.GetComponentsInChildren<Transform>()) transform.gameObject.layer = 29;
                var mesh = root.GetComponentInChildren<MeshFilter>().sharedMesh;
                mesh.colors = Enumerable.Repeat(Color.white,mesh.vertexCount).ToArray();
                // Fixed physical planes, not derived from mesh UV or production vertices.
                var a = new[] { new Vector3(-1,-1,-1),new Vector3(1,-1,1),new Vector3(-1,-1,1),
                    new Vector3(1,-1,-1),new Vector3(-1,1,-1),new Vector3(-1,-1,1) }[face];
                var b = new[] { new Vector3(-1,1,-1),new Vector3(1,1,1),new Vector3(-1,1,1),
                    new Vector3(1,1,-1),new Vector3(-1,1,1),new Vector3(-1,-1,-1) }[face];
                var d = new[] { new Vector3(1,-1,-1),new Vector3(-1,-1,1),new Vector3(-1,-1,-1),
                    new Vector3(1,-1,1),new Vector3(1,1,-1),new Vector3(1,-1,1) }[face];
                var normals = new[] { Vector3.back,Vector3.forward,Vector3.left,Vector3.right,Vector3.up,Vector3.down };
                var camera = cameraObject.AddComponent<Camera>();
                camera.enabled = false; camera.orthographic = true; camera.orthographicSize = .18f;
                camera.nearClipPlane = .01f; camera.farClipPlane = 4;
                camera.cullingMask = 1 << 29; camera.clearFlags = CameraClearFlags.SolidColor;
                camera.backgroundColor = Color.magenta; camera.allowHDR = false; camera.allowMSAA = false;
                camera.transform.position = normals[face];
                camera.transform.rotation = Quaternion.LookRotation(-normals[face], face < 4 ? Vector3.up : Vector3.forward);
                camera.targetTexture = target; RenderSettings.fog = false;
                camera.Render(); RenderTexture.active = target;
                readback.ReadPixels(new Rect(0,0,128,128),0,0); readback.Apply();
                var corners = ReferenceBoxCorners(face,mirror);
                foreach (var s in new[] { .25f,.75f }) foreach (var t in new[] { .25f,.75f })
                {
                    var physical = a + (d-a)*s + (b-a)*t;
                    var screen = camera.WorldToScreenPoint(Vector3.Scale(physical,new Vector3(1,1.5f,2))/16f);
                    var pixel = readback.GetPixel(Mathf.FloorToInt(screen.x),Mathf.FloorToInt(screen.y));
                    var uv = corners[0] + (corners[3]-corners[0])*s + (corners[1]-corners[0])*t;
                    Assert.That(pixel.r,Is.EqualTo(uv.x/64f).Within(.01f),"U face " + face);
                    Assert.That(pixel.g,Is.EqualTo(uv.y/32f).Within(.035f),"V face " + face);
                    Assert.That(pixel.b,Is.EqualTo(.4f).Within(.02f),"visible outward face " + face);
                }
            }
            finally
            {
                RenderTexture.active = previous; RenderSettings.fog = fog;
                Object.DestroyImmediate(cameraObject); Object.DestroyImmediate(root); Object.DestroyImmediate(material);
                Object.DestroyImmediate(texture); Object.DestroyImmediate(readback); target.Release(); Object.DestroyImmediate(target);
            }
        }

        private static string MirrorFixture(bool modern, bool boneMirror)
        {
            const string cube = "{\"origin\":[1,2,3],\"size\":[2,3,4],\"uv\":[5,6]";
            var bones = "\"bones\":[{\"name\":\"body\",\"pivot\":[0,0,0],\"mirror\":" +
                (boneMirror ? "true" : "false") + ",\"cubes\":[" + cube + "}," + cube + ",\"mirror\":false}," +
                cube + ",\"mirror\":true}]},{\"name\":\"child\",\"parent\":\"body\",\"pivot\":[0,4,0],\"cubes\":[" + cube + "}]}]";
            return modern ? "{\"format_version\":\"1.12.0\",\"minecraft:geometry\":[{\"description\":{\"identifier\":\"geometry.mirror\",\"texture_width\":64,\"texture_height\":32}," + bones + "}]}" :
                "{\"format_version\":\"1.8.0\",\"geometry.mirror\":{\"texturewidth\":64,\"textureheight\":32," + bones + "}}";
        }

        [TestCase(false, false)]
        [TestCase(false, true)]
        [TestCase(true, false)]
        [TestCase(true, true)]
        public void CubeMirrorOverridesItsOwnBoneDefaultWithoutInheritingParent(bool modern, bool boneMirror)
        {
            var geometry = DemoMinecraftEntityGeometryParser.Parse(MirrorFixture(modern, boneMirror), "geometry.mirror");
            Assert.That(geometry.Bones[0].Cubes.Select(cube => cube.Mirror), Is.EqualTo(new[] { boneMirror, false, true }));
            Assert.That(geometry.Bones[1].Cubes[0].Mirror, Is.False, "child bone does not inherit parent bone mirror");
        }

        [Test]
        public void GuardianHeadKeepsExplicitUnmirroredCubesAndMirrorsOnlyDefaultedCubes()
        {
            var source = Resources.Load<TextAsset>("DemoWorld/entity_models/entity_guardian");
            Assert.That(source, Is.Not.Null);
            var geometry = DemoMinecraftEntityGeometryParser.Parse(source.text, "geometry.guardian.v1.8");
            Assert.That(geometry.Bones.Single(bone => bone.Name == "head").Cubes.Select(cube => cube.Mirror),
                Is.EqualTo(new[] { false, false, true, true, true }));
            Assert.That(geometry.Bones.Where(bone => bone.Name != "head").SelectMany(bone => bone.Cubes).All(cube => !cube.Mirror), Is.True);
        }

        [TestCase(false)]
        [TestCase(true)]
        public void InheritedMirrorChangesNorthFaceUvButNotVerticesNormalsOrTriangles(bool modern)
        {
            var geometry = DemoMinecraftEntityGeometryParser.Parse(MirrorFixture(modern, true), "geometry.mirror");
            var root = new GameObject("MirrorUv");
            var material = new Material(Shader.Find("Standard"));
            try
            {
                Assert.That(DemoMinecraftEntityModelBuilder.TryBuild(root.transform, geometry,
                    new DemoMinecraftEntityModelBuilder.BuildOptions { PrimaryTextureKey = "test", TextureWidth = 64,
                        TextureHeight = 32, MaterialProvider = _ => material }), Is.True);
                var meshes = root.transform.Find("Model/Bone_body").GetComponentsInChildren<MeshFilter>()
                    .Where(value => value.transform.parent.name == "Bone_body").Select(value => value.sharedMesh).ToArray();
                Assert.That(meshes.Length, Is.EqualTo(3));
                var inherited = meshes[0]; var plain = meshes[1]; var explicitMirror = meshes[2];
                Assert.That(inherited.vertices, Is.EqualTo(plain.vertices));
                Assert.That(inherited.normals, Is.EqualTo(plain.normals));
                Assert.That(inherited.triangles, Is.EqualTo(plain.triangles));
                Assert.That(inherited.uv, Is.EqualTo(explicitMirror.uv));
                // North face box UV: u=5,dz=4,dx=2. Mirroring swaps 9/64 with 11/64.
                // UI-083 corrects the older assertion's missing source-X reflection.
                Assert.That(inherited.uv.Take(4), Is.EqualTo(new[] { new Vector2(9f/64,19f/32),
                    new Vector2(9f/64,22f/32),new Vector2(11f/64,22f/32),new Vector2(11f/64,19f/32) }));
                Assert.That(plain.uv[0], Is.EqualTo(new Vector2(11f/64,19f/32)));
            }
            finally { Object.DestroyImmediate(root); Object.DestroyImmediate(material); }
        }

        [TestCase(true, 0f)]
        [TestCase(false, 0f)]
        [TestCase(true, 0.23f)]
        [TestCase(false, 0.23f)]
        public void BlazeOriginalRodsOrbitInThreeSourceRings(bool player, float seconds)
        {
            var root = new GameObject("BlazeOrbit");
            var material = new Material(Shader.Find("Standard"));
            try
            {
                Assert.That(DemoMinecraftModelFactory.TryBuild(root.transform, "nt_003", player, _ => material), Is.True);
                var animator = root.GetComponent<DemoEntityIdleAnimator>();
                animator.SampleForAudit(seconds);
                for (var rod = 0; rod < 12; rod++)
                {
                    var ring = rod / 4;
                    var radius = ring == 0 ? 9f : ring == 1 ? 7f : 5f;
                    var rate = ring == 0 ? -360f : ring == 1 ? 108f : -180f;
                    var phase = rod % 4 * 90f + (ring == 0 ? 0f : ring == 1 ? 45f : 27f);
                    var angle = (phase + rate * seconds) * Mathf.Deg2Rad;
                    var height = (ring == 0 ? 2f : ring == 1 ? -2f : -11f) +
                        Mathf.Cos((rod * (ring == 2 ? 1.5f : 2f) + seconds * 20f) * 14.32f * Mathf.Deg2Rad);
                    var bone = root.transform.Find("Model/Bone_upperBodyParts" + rod);
                    Assert.That(Vector3.Distance(bone.localPosition,
                        new Vector3(-Mathf.Cos(angle) * radius, 24f + height, Mathf.Sin(angle) * radius) / 16f),
                        Is.LessThan(0.0001f), "original source rod position " + rod);
                    Assert.That(Vector3.Distance(bone.GetComponentInChildren<MeshFilter>().sharedMesh.bounds.center,
                        new Vector3(-1, -4, 1) / 16f), Is.LessThan(0.0001f), "do not rewrite source pivot " + rod);
                    Assert.That(Quaternion.Angle(bone.localRotation, Quaternion.identity), Is.LessThan(0.001f));
                }
                Assert.That(animator.TrackCount, Is.EqualTo(13));
                Assert.That(root.GetComponentsInChildren<MeshRenderer>().Length, Is.EqualTo(13));
                animator.SampleForAudit(0);
                Assert.That(EncapsulateAll(root.GetComponentsInChildren<MeshRenderer>()).min.y, Is.EqualTo(0.3f).Within(0.001f));
                Assert.That(root.transform.eulerAngles.y, Is.EqualTo(player ? 180 : 0).Within(0.001f));
            }
            finally { Object.DestroyImmediate(root); Object.DestroyImmediate(material); }
        }

        [TestCase(true)]
        [TestCase(false)]
        public void GuardianStaticPoseAttachesEyeTailAndTwelveOutwardSpikes(bool player)
        {
            var root = new GameObject("GuardianStanding");
            var material = new Material(Shader.Find("Standard"));
            try
            {
                Assert.That(DemoMinecraftModelFactory.TryBuild(root.transform, "or_004", player, _ => material), Is.True);
                var head = root.transform.Find("Model/Bone_head");
                var eye = head.Find("Bone_eye");
                Assert.That(eye.localPosition, Is.EqualTo(new Vector3(0, 24, -8.25f) / 16f));
                var firstTail = head.Find("Bone_tailpart0");
                var secondTail = firstTail.Find("Bone_tailpart1");
                var tip = secondTail.Find("Bone_tailpart2");
                Assert.That(secondTail.localPosition, Is.EqualTo(new Vector3(1.5f, -0.5f, 14) / 16f));
                Assert.That(tip.localPosition, Is.EqualTo(new Vector3(-0.5f, -0.5f, 6) / 16f));
                var centers = new[]
                {
                    new Vector3(0,16,8), new Vector3(0,16,-8), new Vector3(-8,16,0), new Vector3(8,16,0),
                    new Vector3(8,8,-8), new Vector3(-8,8,-8), new Vector3(-8,8,8), new Vector3(8,8,8),
                    new Vector3(0,0,8), new Vector3(0,0,-8), new Vector3(-8,0,0), new Vector3(8,0,0)
                };
                for (var index = 0; index < 12; index++)
                {
                    var spike = head.Find("Bone_spikepart" + index);
                    Assert.That(spike.localPosition, Is.EqualTo(centers[index] / 16f), "source spike center " + index);
                    var radial = (centers[index] - new Vector3(0, 8, 0)).normalized;
                    Assert.That(Vector3.Dot(spike.localRotation * Vector3.up, radial), Is.GreaterThan(0.999f), "outward spike " + index);
                }
                Assert.That(root.GetComponentsInChildren<MeshRenderer>().Length, Is.EqualTo(22), "preserve all original cubes");
                Assert.That(EncapsulateAll(root.GetComponentsInChildren<MeshRenderer>()).min.y, Is.EqualTo(0.4f).Within(0.001f));
                var animator = root.GetComponent<DemoEntityIdleAnimator>();
                Assert.That(animator.TrackCount, Is.EqualTo(4));
                animator.SampleForAudit(0.23f);
                Assert.That(secondTail.localPosition, Is.EqualTo(new Vector3(1.5f, -0.5f, 14) / 16f));
                Assert.That(Quaternion.Angle(firstTail.localRotation, Quaternion.identity), Is.GreaterThan(0.1f));
                Assert.That(root.transform.eulerAngles.y, Is.EqualTo(player ? 180 : 0).Within(0.001f));
            }
            finally { Object.DestroyImmediate(root); Object.DestroyImmediate(material); }
        }

        [TestCase("bone", 90, 0, -1, 1, -2)]
        [TestCase("bone", 0, 90, -1, -2, 1)]
        [TestCase("bone", 90, 90, -1, -1, -2)]
        [TestCase("array", 90, 0, -1, 1, -2)]
        [TestCase("array", 0, 90, -1, -2, 1)]
        [TestCase("array", 90, 90, -1, -1, -2)]
        [TestCase("axis", 90, 0, -1, 1, -2)]
        [TestCase("axis", 0, 90, -1, -2, 1)]
        public void MirroredSourceYawAndRollMatchAnalyticCoordinates(string format, int yaw, int roll, int x, int y, int z)
        {
            var cube = new DemoEntityCube { Origin = new[] { 1f, 0f, 0f }, Size = new[] { 2f, 2f, 2f } };
            var bone = new DemoEntityBone { Name = "body", Cubes = new List<DemoEntityCube> { cube } };
            var degrees = new[] { 0f, (float)yaw, (float)roll };
            if (format == "array") { cube.CompositeRotation = degrees; cube.RotationPivot = new float[3]; }
            else if (format == "axis") { cube.RotationAxis = yaw != 0 ? "y" : "z"; cube.RotationAngle = yaw != 0 ? yaw : roll; cube.RotationPivot = new float[3]; }
            else bone.Rotation = degrees;
            var geometry = new DemoEntityGeometry { Bones = new List<DemoEntityBone> { bone } };
            var root = new GameObject("AnalyticRotation");
            var material = new Material(Shader.Find("Standard"));
            try
            {
                Assert.That(DemoMinecraftEntityModelBuilder.TryBuild(root.transform, geometry,
                    new DemoMinecraftEntityModelBuilder.BuildOptions { PrimaryTextureKey = "test", MaterialProvider = _ => material }), Is.True);
                // Starting center after X mirror: (-2,1,1). ZYX product applies yaw before roll.
                var center = root.GetComponentInChildren<MeshRenderer>().bounds.center;
                Assert.That(Vector3.Distance(center, new Vector3(x, y, z) / 16f), Is.LessThan(0.0001f));
            }
            finally { Object.DestroyImmediate(root); Object.DestroyImmediate(material); }
        }

        [TestCase(false)]
        [TestCase(true)]
        public void BedrockThreeAxisRotationAppliesXThenYThenZ(bool cubeRotation)
        {
            var cube = new DemoEntityCube { Origin = new[] { 1f, 0f, 0f }, Size = new[] { 2f, 2f, 2f } };
            var bone = new DemoEntityBone { Name = "body", Cubes = new List<DemoEntityCube> { cube } };
            if (cubeRotation) { cube.CompositeRotation = new[] { 90f, 90f, 90f }; cube.RotationPivot = new float[3]; }
            else bone.Rotation = new[] { 90f, 90f, 90f };
            var root = new GameObject("ThreeAxisOrder");
            var material = new Material(Shader.Find("Standard"));
            try
            {
                Assert.That(DemoMinecraftEntityModelBuilder.TryBuild(root.transform,
                    new DemoEntityGeometry { Bones = new List<DemoEntityBone> { bone } },
                    new DemoMinecraftEntityModelBuilder.BuildOptions { PrimaryTextureKey = "test", MaterialProvider = _ => material }), Is.True);
                // Independent right-angle sequence: (-2,1,1) -> (-2,1,-1) -> (1,1,-2) -> (-1,1,-2).
                Assert.That(Vector3.Distance(root.GetComponentInChildren<MeshRenderer>().bounds.center,
                    new Vector3(-1, 1, -2) / 16f), Is.LessThan(0.0001f));
            }
            finally { Object.DestroyImmediate(root); Object.DestroyImmediate(material); }
        }

        [TestCase(true)]
        [TestCase(false)]
        public void SpiderDefaultPoseSpreadsEightLegsDownwardAndIdleRetainsStandingPose(bool player)
        {
            var root = new GameObject("SpiderStanding");
            var material = new Material(Shader.Find("Standard"));
            try
            {
                Assert.That(DemoMinecraftModelFactory.TryBuild(root.transform, "cd_002", player, _ => material), Is.True);
                var body = root.transform.Find("Model/Bone_body0");
                var directions = new List<Vector3>();
                var sourceYaw = new[] { 45f, -45f, 22.5f, -22.5f, -22.5f, 22.5f, -45f, 45f };
                var sourceRoll = new[] { -45f, 45f, -33.3f, 33.3f, -33.3f, 33.3f, -45f, 45f };
                for (var index = 0; index < 8; index++)
                {
                    var leg = body.Find("Bone_leg" + index);
                    var direction = leg.localRotation * (index % 2 == 0 ? Vector3.right : Vector3.left);
                    var yaw = sourceYaw[index] * Mathf.Deg2Rad;
                    var roll = sourceRoll[index] * Mathf.Deg2Rad;
                    var side = index % 2 == 0 ? 1f : -1f;
                    // Independent source ZYX direction: yaw the mirrored X axis, then roll it.
                    var expected = side * new Vector3(Mathf.Cos(yaw) * Mathf.Cos(roll),
                        Mathf.Cos(yaw) * Mathf.Sin(roll), Mathf.Sin(yaw));
                    Assert.That(Vector3.Distance(direction, expected), Is.LessThan(0.0001f), "source leg " + index);
                    Assert.That(direction.y, Is.LessThan(-0.49f), "leg " + index + " must descend");
                    Assert.That(direction.z * (index < 4 ? 1 : -1), Is.GreaterThan(0.25f));
                    Assert.That(directions.All(prior => Vector3.Distance(prior, direction) > 0.1f), Is.True);
                    directions.Add(direction);
                }
                Assert.That(EncapsulateAll(root.GetComponentsInChildren<MeshRenderer>()).min.y, Is.EqualTo(0).Within(0.001f));
                var animator = root.GetComponent<DemoEntityIdleAnimator>();
                Assert.That(animator.TrackCount, Is.EqualTo(8));
                animator.SampleForAudit(0.23f);
                for (var index = 0; index < 8; index++)
                {
                    var direction = body.Find("Bone_leg" + index).localRotation * (index % 2 == 0 ? Vector3.right : Vector3.left);
                    Assert.That(Vector3.Angle(direction, directions[index]), Is.LessThanOrEqualTo(3.001f));
                }
                Assert.That(root.transform.eulerAngles.y, Is.EqualTo(player ? 180 : 0).Within(0.001f));
            }
            finally { Object.DestroyImmediate(root); Object.DestroyImmediate(material); }
        }

        [TestCase(true)]
        [TestCase(false)]
        public void EndermanStandingPoseAlignsHeadAboveTorsoWithoutMovingInnerHeadTwice(bool player)
        {
            var root = new GameObject("EndermanPoseAudit");
            var materials = new List<Material>();
            try
            {
                Assert.That(DemoMinecraftModelFactory.TryBuild(root.transform, "ed_003", player, key =>
                {
                    var material = DemoWorldAssetProvider.CreateEntityMaterial("EndermanPose_" + key, Color.white, key);
                    materials.Add(material); return material;
                }), Is.True);
                var body = root.transform.Find("Model/Bone_body");
                var head = body.Find("Bone_head");
                var inner = head.Find("Bone_hat");
                Assert.That(head.localPosition.y, Is.EqualTo(0).Within(0.00001f));
                Assert.That(inner.localPosition.y, Is.EqualTo(0).Within(0.00001f));
                var headMesh = head.GetComponentInChildren<MeshFilter>().sharedMesh;
                var torso = body.GetComponentsInChildren<MeshFilter>().Single(filter => filter.transform.parent == body).sharedMesh;
                Assert.That(headMesh.bounds.min.y, Is.EqualTo(0).Within(0.00001f));
                Assert.That(torso.bounds.max.y, Is.EqualTo(0).Within(0.00001f));
                var innerMesh = inner.GetComponentInChildren<MeshFilter>().sharedMesh;
                Assert.That(innerMesh.bounds.max.y, Is.LessThan(headMesh.bounds.max.y));
                Assert.That(root.GetComponent<DemoEntityIdleAnimator>().TrackCount, Is.GreaterThan(0));
                Assert.That(root.transform.eulerAngles.y, Is.EqualTo(player ? 180 : 0).Within(0.001f));
            }
            finally { Object.DestroyImmediate(root); foreach (var material in materials) Object.DestroyImmediate(material); }
        }

        [TestCase(3, true, 0.7f, 0.9f)]
        [TestCase(3, false, 0f, 0.15f)]
        [TestCase(0, true, 0f, 0.15f)]
        [TestCase(255, true, 0.3f, 0.5f)]
        public void EntityShaderGpuRetainsEyesRejectsPaddingAndKeepsBodyShading(int alpha, bool enabled, float minimumRed, float maximumRed)
        {
            AssertEntityPixel(alpha, enabled, minimumRed, maximumRed, false, false);
        }

        [TestCase(0, false, 0.3f, 0.5f)]
        [TestCase(1, false, 0.3f, 0.5f)]
        [TestCase(3, true, 0.3f, 0.5f)]
        [TestCase(255, false, 0.3f, 0.5f)]
        [TestCase(255, true, 0.15f, 0.25f)]
        public void SheepColorMaskGpuPreservesSkinShadingAndOnlyTintsWool(int alpha, bool tinted, float minimumRed, float maximumRed)
        {
            AssertEntityPixel(alpha, false, minimumRed, maximumRed, true, tinted);
        }

        [TestCase("entity_sheep", true)]
        [TestCase("entity_sheep_baby", true)]
        [TestCase("entity_enderman", false)]
        [TestCase("entity_bee", false)]
        public void AlphaColorMaskIsRegisteredOnlyForSheep(string key, bool expected)
        {
            var material = DemoWorldAssetProvider.CreateEntityMaterial("MaskContract", Color.white, key);
            try
            {
                Assert.That(DemoMinecraftModelFactory.UsesAlphaColorMask(key), Is.EqualTo(expected));
                Assert.That(material.GetFloat("_UseAlphaColorMask"), Is.EqualTo(expected ? 1 : 0));
            }
            finally { Object.DestroyImmediate(material); }
        }

        private void AssertEntityPixel(int alpha, bool enabled, float minimumRed, float maximumRed, bool colorMask, bool tinted)
        {
            var rig = new GameObject("AlphaGpuCamera");
            var quad = GameObject.CreatePrimitive(PrimitiveType.Quad);
            var mesh = Object.Instantiate(quad.GetComponent<MeshFilter>().sharedMesh);
            var texture = new Texture2D(1, 1, TextureFormat.RGBA32, false, true);
            var readback = new Texture2D(16, 16, TextureFormat.RGBA32, false, true);
            var target = new RenderTexture(16, 16, 16, RenderTextureFormat.ARGB32, RenderTextureReadWrite.Linear);
            var material = new Material(Shader.Find("BiomeRivals/Demo/Entity"));
            var previousTarget = RenderTexture.active;
            var previousFog = RenderSettings.fog;
            try
            {
                RenderSettings.fog = false;
                texture.SetPixel(0, 0, new Color(0.8f, 0.3f, 0.9f, alpha / 255f));
                texture.Apply();
                texture.filterMode = FilterMode.Point;
                mesh.colors = Enumerable.Repeat(new Color(0.5f, 0.5f, 0.5f, 1), mesh.vertexCount).ToArray();
                quad.GetComponent<MeshFilter>().sharedMesh = mesh;
                quad.layer = 29;
                quad.GetComponent<MeshRenderer>().sharedMaterial = material;
                material.mainTexture = texture;
                material.SetFloat("_UseLowAlphaEmission", enabled ? 1 : 0);
                material.SetFloat("_UseAlphaColorMask", colorMask ? 1 : 0);
                material.SetColor("_MaskColor", tinted ? new Color(0.5f, 1, 1, 1) : Color.white);
                material.SetFloat("_Cutoff", enabled ? 0.5f / 255f : 0.1f);
                var camera = rig.AddComponent<Camera>();
                camera.enabled = false;
                camera.cullingMask = 1 << 29;
                camera.orthographic = true;
                camera.orthographicSize = 0.6f;
                camera.transform.position = new Vector3(0, 0, -2);
                camera.clearFlags = CameraClearFlags.SolidColor;
                camera.backgroundColor = new Color(0.05f, 0.05f, 0.05f, 1);
                camera.allowHDR = false;
                camera.allowMSAA = false;
                camera.targetTexture = target;
                target.Create();
                camera.Render();
                RenderTexture.active = target;
                readback.ReadPixels(new Rect(0, 0, 16, 16), 0, 0);
                readback.Apply();
                Assert.That(readback.GetPixel(8, 8).r, Is.InRange(minimumRed, maximumRed));
            }
            finally
            {
                RenderSettings.fog = previousFog;
                RenderTexture.active = previousTarget;
                Object.DestroyImmediate(rig);
                Object.DestroyImmediate(quad);
                Object.DestroyImmediate(mesh);
                Object.DestroyImmediate(material);
                Object.DestroyImmediate(texture);
                Object.DestroyImmediate(readback);
                target.Release(); Object.DestroyImmediate(target);
            }
        }

        [TestCase("entity_enderman", true)]
        [TestCase("entity_cave_spider", true)]
        [TestCase("entity_villager_desert", false)]
        [TestCase("entity_bee", false)]
        public void LowAlphaEmissionIsRegisteredAndDoesNotMakePaddingOpaque(string textureKey, bool expected)
        {
            Assert.That(DemoMinecraftModelFactory.UsesLowAlphaEmission(textureKey), Is.EqualTo(expected));
            var material = DemoWorldAssetProvider.CreateEntityMaterial("AlphaPolicy", Color.white, textureKey);
            try
            {
                Assert.That(material.GetFloat("_UseLowAlphaEmission"), Is.EqualTo(expected ? 1f : 0f));
                var cutoff = material.GetFloat("_Cutoff");
                Assert.That(cutoff, Is.GreaterThan(0));
                Assert.That(cutoff, Is.EqualTo(expected ? 0.5f / 255f : 0.1f).Within(0.000001f));
                if (expected) Assert.That(3f / 255f, Is.GreaterThan(cutoff));
            }
            finally { Object.DestroyImmediate(material); }
        }

        [Test]
        public void RawEndermanEyePixelsAreLowAlphaNotMissingColour()
        {
            // Read original local source bytes without changing import settings or source alpha.
            var path = System.IO.Path.Combine(Application.dataPath, "Generated/MinecraftWorldTextures/Resources/DemoWorld/entity_enderman.tga");
            var bytes = System.IO.File.ReadAllBytes(path);
            Assert.That(bytes[2], Is.EqualTo(2), "Fixture expects uncompressed true-color source TGA.");
            Assert.That(bytes[16], Is.EqualTo(32));
            var width = System.BitConverter.ToUInt16(bytes, 12);
            var height = System.BitConverter.ToUInt16(bytes, 14);
            Assert.That(width, Is.EqualTo(64)); Assert.That(height, Is.EqualTo(32));
            var offset = 18 + bytes[0];
            var eyeCount = 0;
            var zeroAlphaWithColour = 0;
            for (var index = 0; index < width * height; index++)
            {
                var pixel = offset + index * 4;
                if (bytes[pixel + 3] == 3 && bytes[pixel] == 250 && bytes[pixel + 2] > 200) eyeCount++;
                if (bytes[pixel + 3] == 0 && (bytes[pixel] != 0 || bytes[pixel + 1] != 0 || bytes[pixel + 2] != 0)) zeroAlphaWithColour++;
            }
            Assert.That(eyeCount, Is.EqualTo(6));
            Assert.That(zeroAlphaWithColour, Is.EqualTo(0));
        }

        [Test]
        public void RawCaveSpiderEyesHaveTwentyLowAlphaRedTexels()
        {
            var path = System.IO.Path.Combine(Application.dataPath,
                "Generated/MinecraftWorldTextures/Resources/DemoWorld/entity_cave_spider.tga");
            var bytes = System.IO.File.ReadAllBytes(path);
            Assert.That(bytes[2], Is.EqualTo(2)); Assert.That(bytes[16], Is.EqualTo(32));
            Assert.That(System.BitConverter.ToUInt16(bytes, 12), Is.EqualTo(64));
            Assert.That(System.BitConverter.ToUInt16(bytes, 14), Is.EqualTo(32));
            var count = 0;
            for (var index = 0; index < 64 * 32; index++)
            {
                var pixel = 18 + bytes[0] + index * 4;
                if (bytes[pixel + 3] == 3 && bytes[pixel + 2] > 60) count++;
            }
            Assert.That(count, Is.EqualTo(20));
        }

        [TestCase(true)]
        [TestCase(false)]
        public void DesertVillagerUsesSkinAndBiomeOnOneMeshSet(bool player)
        {
            var root = new GameObject("DesertVillagerSurface");
            var materials = new List<Material>();
            try
            {
                Assert.That(DemoMinecraftModelFactory.TryGetSurfaceBaseTextureKey("entity_villager_desert", out var skinKey), Is.True);
                Assert.That(skinKey, Is.EqualTo("entity_villager"));
                Assert.That(DemoMinecraftModelFactory.TryBuild(root.transform, "db_003", player, key =>
                {
                    var material = DemoWorldAssetProvider.CreateEntityMaterial("Test_" + key, Color.white, key);
                    materials.Add(material);
                    return material;
                }), Is.True);
                foreach (var material in materials)
                {
                    Assert.That(material.shader.name, Is.EqualTo("BiomeRivals/Demo/Entity"));
                    Assert.That(material.mainTexture, Is.SameAs(DemoWorldAssetProvider.LoadBlockTexture("entity_villager")));
                    Assert.That(material.GetTexture("_SurfaceOverlayTex"), Is.SameAs(DemoWorldAssetProvider.LoadBlockTexture("entity_villager_desert")));
                    Assert.That(material.GetFloat("_UseSurfaceOverlay"), Is.EqualTo(1));
                    Assert.That(material.GetFloat("_Cutoff"), Is.EqualTo(0.1f).Within(0.00001f));
                }
                var meshes = root.GetComponentsInChildren<MeshFilter>();
                var model = Resources.Load<TextAsset>("DemoWorld/entity_models/entity_villager_desert");
                var geometry = DemoMinecraftEntityGeometryParser.Parse(model.text, "geometry.villager_v2");
                Assert.That(meshes.Length, Is.EqualTo(geometry.Bones.Sum(bone => bone.Cubes.Count)));
                Assert.That(root.transform.eulerAngles.y, Is.EqualTo(player ? 180 : 0).Within(0.001f));
                Assert.That(root.GetComponent<DemoEntityIdleAnimator>().TrackCount, Is.GreaterThan(0));
            }
            finally
            {
                Object.DestroyImmediate(root);
                foreach (var material in materials) Object.DestroyImmediate(material);
            }
        }

        [Test]
        public void PlainVillagerRemainsSingleSurfaceAndDisabledAssetsRejectComposite()
        {
            Assert.That(DemoMinecraftModelFactory.TryGetSurfaceBaseTextureKey("entity_villager", out _), Is.False);
            Assert.That(DemoMinecraftModelFactory.TryGetSurfaceBaseTextureKey("unknown", out _), Is.False);
            var material = DemoWorldAssetProvider.CreateEntityMaterial("PlainVillagerSurface", Color.white, "entity_villager");
            var original = DemoWorldAssetProvider.LocalAssetsEnabled;
            try
            {
                Assert.That(material.mainTexture, Is.SameAs(DemoWorldAssetProvider.LoadBlockTexture("entity_villager")));
                Assert.That(material.GetFloat("_UseSurfaceOverlay"), Is.EqualTo(0));
                DemoWorldAssetProvider.LocalAssetsEnabled = false;
                Assert.Throws<MissingReferenceException>(() => DemoWorldAssetProvider.CreateEntityMaterial("MissingSkin", Color.white, "entity_villager_desert"));
            }
            finally { DemoWorldAssetProvider.LocalAssetsEnabled = original; Object.DestroyImmediate(material); }
        }

        [Test]
        public void RuntimeEntityShaderIsExplicitlyIncludedInPlayerBuilds()
        {
            var shader = UnityEditor.AssetDatabase.LoadAssetAtPath<Shader>("Assets/Game/Demo/Art/DemoEntity.shader");
            Assert.That(shader, Is.Not.Null);
            var settings = UnityEditor.AssetDatabase.LoadAllAssetsAtPath("ProjectSettings/GraphicsSettings.asset");
            Assert.That(settings.Length, Is.GreaterThan(0));
            var serialized = new UnityEditor.SerializedObject(settings[0]);
            var included = serialized.FindProperty("m_AlwaysIncludedShaders");
            Assert.That(included, Is.Not.Null);
            var matches = 0;
            for (var index = 0; index < included.arraySize; index++)
                if (included.GetArrayElementAtIndex(index).objectReferenceValue == shader) matches++;
            Assert.That(matches, Is.EqualTo(1), "Shader.Find alone does not keep the runtime entity shader in a Player.");
        }

        [Test]
        public void AuditIdleSamplingIsRepeatableAndRejectsInvalidTime()
        {
            var root = new GameObject("AuditIdleRoot");
            try
            {
                var bone = new GameObject("Bone_head").transform;
                bone.SetParent(root.transform, false);
                bone.localPosition = new Vector3(1, 2, 3);
                bone.localRotation = Quaternion.Euler(12, 25, 0);
                var initialPosition = bone.localPosition;
                var initialRotation = bone.localRotation;
                var animator = DemoEntityIdleAnimator.Attach(root, new[]
                {
                    new DemoEntityIdleAnimator.IdleTrackSpec
                    { BoneName = "head", Frequency = 1, AmplitudeDegrees = 15, PositionAmplitude = 0.2f, Axis = Vector3.up }
                });
                animator.SampleForAudit(0.23f);
                var rotation = bone.localRotation;
                var position = bone.localPosition;
                Assert.That(Quaternion.Angle(rotation, initialRotation), Is.GreaterThan(1));
                Assert.That((position - initialPosition).magnitude, Is.GreaterThan(0.1f));
                animator.SampleForAudit(0);
                Assert.That(Quaternion.Angle(bone.localRotation, initialRotation), Is.LessThan(0.001f));
                Assert.That(bone.localPosition, Is.EqualTo(initialPosition));
                animator.SampleForAudit(0.23f);
                Assert.That(Quaternion.Angle(bone.localRotation, rotation), Is.LessThan(0.001f));
                Assert.That(bone.localPosition, Is.EqualTo(position));
                foreach (var invalid in new[] { -1f, float.NaN, float.PositiveInfinity, float.NegativeInfinity })
                    Assert.Throws<System.ArgumentOutOfRangeException>(() => animator.SampleForAudit(invalid));
                Assert.That(bone.localPosition, Is.EqualTo(position));
            }
            finally { Object.DestroyImmediate(root); }
        }

        private const string ModernGeometryJson = @"{
  ""format_version"": ""1.12.0"",
  ""minecraft:geometry"": [
    {
      ""description"": { ""identifier"": ""geometry.test_creature"", ""texture_width"": 32, ""texture_height"": 32 },
      ""bones"": [
        { ""name"": ""root"", ""pivot"": [0, 0, 0] },
        {
          ""name"": ""body"", ""parent"": ""root"", ""pivot"": [0, 4, 0],
          ""cubes"": [ { ""origin"": [-2, 0, -2], ""size"": [4, 8, 4], ""uv"": [0, 0] } ]
        },
        {
          ""name"": ""mirror_arm"", ""parent"": ""root"", ""pivot"": [3, 6, 0],
          ""cubes"": [ { ""origin"": [2, 4, -1], ""size"": [2, 4, 2], ""uv"": [8, 0], ""mirror"": true } ]
        }
      ]
    }
  ]
}";

        private const string LegacyGeometryJson = @"{
  ""format_version"": ""1.8.0"",
  ""geometry.legacy_creature"": {
    ""texturewidth"": 64,
    ""textureheight"": 32,
    ""bones"": [
      {
        ""name"": ""body"", ""pivot"": [0, 0, 0], ""bind_pose_rotation"": [90, 0, 0],
        ""cubes"": [ { ""origin"": [-3, 13, -5], ""size"": [8, 16, 6], ""uv"": [28, 8] } ]
      }
    ]
  }
}";

        private const string ModernSelectionJson = "{\"minecraft:geometry\":[" +
            "{\"description\":{\"identifier\":\"geometry.first\"},\"bones\":[]}," +
            "{\"description\":{\"identifier\":\"geometry.second\"},\"bones\":[]}]}";
        private const string LegacySelectionJson = "{\"geometry.first\":{\"bones\":[]}," +
            "\"geometry.second\":{\"texturewidth\":128,\"bones\":[]}}";

        [TestCase(false)]
        [TestCase(true)]
        public void ExplicitGeometrySelectionChoosesNonFirstEntry(bool modern)
        {
            var result = DemoMinecraftEntityGeometryParser.Parse(modern ? ModernSelectionJson : LegacySelectionJson,
                "geometry.second");
            Assert.That(result.Identifier, Is.EqualTo("geometry.second"));
            if (!modern) Assert.That(result.TextureWidth, Is.EqualTo(128));
        }

        [TestCase(false, "geometry.missing")]
        [TestCase(true, "geometry.missing")]
        [TestCase(false, "Geometry.first")]
        [TestCase(true, "Geometry.first")]
        [TestCase(false, "")]
        [TestCase(true, "")]
        [TestCase(false, " ")]
        [TestCase(true, " ")]
        public void ExplicitGeometrySelectionNeverFallsBack(bool modern, string requested)
        {
            Assert.Throws<System.FormatException>(() => DemoMinecraftEntityGeometryParser.Parse(
                modern ? ModernSelectionJson : LegacySelectionJson, requested));
        }

        [TestCase(false)]
        [TestCase(true)]
        public void UnspecifiedGeometryKeepsDocumentedFirstEntryDefault(bool modern)
        {
            Assert.That(DemoMinecraftEntityGeometryParser.Parse(modern ? ModernSelectionJson : LegacySelectionJson).Identifier,
                Is.EqualTo("geometry.first"));
        }

        [Test]
        public void DuplicateModernGeometryIdentifiersAreRejected()
        {
            Assert.Throws<System.FormatException>(() => DemoMinecraftEntityGeometryParser.Parse(
                ModernSelectionJson.Replace("geometry.second", "geometry.first"), "geometry.first"));
        }

        [TestCase("{\"minecraft:geometry\":[null]}")]
        [TestCase("{\"minecraft:geometry\":[{\"bones\":[]}]}")]
        public void MalformedModernGeometryIsRejected(string json)
        {
            Assert.Throws<System.FormatException>(() => DemoMinecraftEntityGeometryParser.Parse(json));
        }

        [TestCase("geometry.derived")]
        [TestCase("geometry.derived:geometry.first")]
        public void ExplicitLegacyDerivedGeometryReportsUnsupportedRatherThanWrongBase(string requested)
        {
            var json = "{\"geometry.first\":{\"bones\":[]},\"geometry.derived:geometry.first\":{\"bones\":[]}}";
            var error = Assert.Throws<System.FormatException>(() => DemoMinecraftEntityGeometryParser.Parse(json, requested));
            Assert.That(error.Message, Does.Contain("derived"));
        }

        [Test]
        public void ParsesModernGeometryWithBonesAndCubes()
        {
            var geometry = DemoMinecraftEntityGeometryParser.Parse(ModernGeometryJson, "geometry.test_creature");
            Assert.That(geometry.Identifier, Is.EqualTo("geometry.test_creature"));
            Assert.That(geometry.TextureWidth, Is.EqualTo(32));
            Assert.That(geometry.TextureHeight, Is.EqualTo(32));
            Assert.That(geometry.Bones, Has.Count.EqualTo(3));
            var body = geometry.Bones.Single(bone => bone.Name == "body");
            Assert.That(body.Parent, Is.EqualTo("root"));
            Assert.That(body.Pivot, Is.EqualTo(new[] { 0f, 4f, 0f }));
            Assert.That(body.Cubes, Has.Count.EqualTo(1));
            Assert.That(body.Cubes[0].Size, Is.EqualTo(new[] { 4f, 8f, 4f }));
            Assert.That(body.Cubes[0].Uv, Is.EqualTo(new[] { 0f, 0f }));
            Assert.That(body.Cubes[0].Mirror, Is.False);
        }

        [Test]
        public void ParsesLegacyGeometryWithBindPoseRotation()
        {
            var geometry = DemoMinecraftEntityGeometryParser.Parse(LegacyGeometryJson);
            Assert.That(geometry.Identifier, Is.EqualTo("geometry.legacy_creature"));
            Assert.That(geometry.TextureWidth, Is.EqualTo(64));
            Assert.That(geometry.TextureHeight, Is.EqualTo(32));
            var body = geometry.Bones.Single(bone => bone.Name == "body");
            Assert.That(body.Rotation, Is.Null);
            Assert.That(body.BindPoseRotation, Is.EqualTo(new[] { 90f, 0f, 0f }));
            Assert.That(body.Cubes[0].Uv, Is.EqualTo(new[] { 28f, 8f }));
        }

        [Test]
        public void OfficialSheepOverlayUsesShortHeadUpperLegsAndOriginalAtlas()
        {
            var json = Resources.Load<TextAsset>("DemoWorld/entity_models/entity_sheep").text;
            var overlay = DemoMinecraftEntityGeometryParser.ParseLegacyOverlay(json,
                "geometry.sheep.v1.8", "geometry.sheep.sheared.v1.8");
            Assert.That(overlay.Bones.Count, Is.EqualTo(6));
            Assert.That(overlay.TextureHeight, Is.EqualTo(64));
            var head = overlay.Bones.Single(bone => bone.Name == "head").Cubes.Single();
            Assert.That(head.Size, Is.EqualTo(new[] { 6f, 6f, 6f }));
            Assert.That(head.Origin[2], Is.EqualTo(-12));
            Assert.That(head.Uv, Is.EqualTo(new[] { 0f, 32f }));
            Assert.That(head.Inflate, Is.EqualTo(0.6f));
            foreach (var bone in overlay.Bones.Where(bone => bone.Name.StartsWith("leg")))
            {
                Assert.That(bone.Cubes.Single().Origin[1], Is.EqualTo(6));
                Assert.That(bone.Cubes.Single().Size[1], Is.EqualTo(6));
                Assert.That(bone.Cubes.Single().Uv[1], Is.EqualTo(48));
            }
            Assert.That(DemoMinecraftModelFactory.TryGetOverlayGeometryId("pf_002", out var id), Is.True);
            Assert.That(id, Is.EqualTo(overlay.Identifier));
            Assert.That(DemoMinecraftModelFactory.TryGetOverlayGeometryId("pf_001", out _), Is.False);
        }

        [TestCase("missing")]
        [TestCase("pivot")]
        [TestCase("parent")]
        [TestCase("rotation")]
        [TestCase("empty")]
        public void ExplicitOverlayRejectsAbsentOrIncompatibleSkeleton(string mutation)
        {
            var json = "{\"geometry.base\":{\"bones\":[{\"name\":\"head\",\"pivot\":[0,1,0]}]}," +
                "\"geometry.wool:geometry.base\":{\"bones\":[{\"name\":\"head\",\"pivot\":[0,1,0]}]}}";
            if (mutation == "pivot") json = json.Replace("geometry.wool:geometry.base\":{\"bones\":[{\"name\":\"head\",\"pivot\":[0,1,0]", "geometry.wool:geometry.base\":{\"bones\":[{\"name\":\"head\",\"pivot\":[0,2,0]");
            if (mutation == "parent") json = json.Replace("geometry.wool:geometry.base\":{\"bones\":[{", "geometry.wool:geometry.base\":{\"bones\":[{\"parent\":\"missing\",");
            if (mutation == "rotation") json = json.Replace("geometry.wool:geometry.base\":{\"bones\":[{", "geometry.wool:geometry.base\":{\"bones\":[{\"rotation\":[90,0,0],");
            if (mutation == "empty") json = json.Replace("geometry.wool:geometry.base\":{\"bones\":[{\"name\":\"head\",\"pivot\":[0,1,0]}]", "geometry.wool:geometry.base\":{\"bones\":[]");
            Assert.Throws<System.FormatException>(() => DemoMinecraftEntityGeometryParser.ParseLegacyOverlay(json,
                mutation == "missing" ? "geometry.missing" : "geometry.wool", "geometry.base"));
        }

        [TestCase(false)]
        [TestCase(true)]
        public void SourceBindingPoseBakesMeshesWithoutMovingChildPivots(bool withBoneRotation)
        {
            var rotation = withBoneRotation ? ", \"rotation\": [30,0,0]" : "";
            var json = "{\"geometry.binding\":{\"bones\":[" +
                "{\"name\":\"body\",\"pivot\":[0,0,0],\"bind_pose_rotation\":[90,0,0]" + rotation +
                ",\"cubes\":[{\"origin\":[-2,-4,-1],\"size\":[4,8,2],\"uv\":[0,0]}]}," +
                "{\"name\":\"child\",\"parent\":\"body\",\"pivot\":[0,8,0]," +
                "\"cubes\":[{\"origin\":[-1,8,-1],\"size\":[2,4,2],\"uv\":[0,0]}]}]}}";
            var root = new GameObject("SourceBindingPose");
            var materials = new List<Material>();
            try
            {
                var options = new DemoMinecraftEntityModelBuilder.BuildOptions
                {
                    PrimaryTextureKey = "base",
                    MaterialProvider = key =>
                    {
                        var material = new Material(Shader.Find("Standard")) { name = key };
                        materials.Add(material);
                        return material;
                    }
                };
                options.Layers.Add(new DemoMinecraftEntityModelBuilder.OverlayLayer { TextureKey = "overlay" });
                Assert.That(DemoMinecraftEntityModelBuilder.TryBuild(root.transform,
                    DemoMinecraftEntityGeometryParser.Parse(json), options), Is.True);
                var body = root.transform.Find("Model/Bone_body");
                Assert.That(Quaternion.Angle(body.localRotation,
                    Quaternion.Euler(withBoneRotation ? -30 : 0, 0, 0)), Is.LessThan(0.001f));
                var child = body.Find("Bone_child");
                Assert.That(child.localPosition, Is.EqualTo(new Vector3(0, 0.5f, 0)));
                // Analytic X rotation: binding does not affect the child's authored position.
                var expectedChild = withBoneRotation ? new Vector3(0, Mathf.Sqrt(3f) / 4f, -0.25f) : new Vector3(0, 0.5f, 0);
                Assert.That(Vector3.Distance(child.position, expectedChild), Is.LessThan(0.0001f));
                foreach (var key in new[] { "base", "overlay" })
                {
                    var mesh = body.Find("Cube_" + key).GetComponent<MeshFilter>().sharedMesh;
                    Assert.That(mesh.bounds.size.y, Is.EqualTo(2f / 16f).Within(0.0001f));
                    Assert.That(mesh.bounds.size.z, Is.EqualTo(8f / 16f).Within(0.0001f));
                }
            }
            finally
            {
                Object.DestroyImmediate(root);
                foreach (var material in materials) Object.DestroyImmediate(material);
            }
        }

        [TestCase(true)]
        [TestCase(false)]
        public void TurtleSourceBindingKeepsHeadAndFlippersInAuthoredFrame(bool player)
        {
            var root = new GameObject("TurtleSourcePose");
            var materials = new List<Material>();
            try
            {
                Assert.That(DemoMinecraftModelFactory.TryBuild(root.transform, "or_005", player, key =>
                {
                    var material = new Material(Shader.Find("Standard")) { name = key };
                    materials.Add(material);
                    return material;
                }), Is.True);
                var body = root.transform.Find("Model/Bone_body");
                Assert.That(Quaternion.Angle(body.localRotation, Quaternion.identity), Is.LessThan(0.001f));
                var shell = body.GetComponentsInChildren<MeshFilter>().First(value => value.transform.parent == body).sharedMesh;
                Assert.That(shell.bounds.size.y, Is.EqualTo(6f / 16f).Within(0.0001f));
                Assert.That(shell.bounds.size.z, Is.EqualTo(20f / 16f).Within(0.0001f));
                foreach (var name in new[] { "head", "leg0", "leg1", "leg2", "leg3", "eggbelly" })
                    Assert.That(Vector3.Dot(body.Find("Bone_" + name).up, Vector3.up), Is.GreaterThan(0.999f));
                var bounds = EncapsulateAll(root.GetComponentsInChildren<MeshRenderer>());
                Assert.That(bounds.min.y, Is.EqualTo(0.05f).Within(0.0001f));
                Assert.That(bounds.size.x, Is.EqualTo(1.8f).Within(0.0001f));
            }
            finally
            {
                Object.DestroyImmediate(root);
                foreach (var material in materials) Object.DestroyImmediate(material);
            }
        }

        [Test]
        public void BuilderCreatesBoneHierarchyAndFitsModel()
        {
            var geometry = DemoMinecraftEntityGeometryParser.Parse(ModernGeometryJson);
            var root = new GameObject("EntityTestRoot");
            try
            {
                var built = DemoMinecraftEntityModelBuilder.TryBuild(root.transform, geometry, new DemoMinecraftEntityModelBuilder.BuildOptions
                {
                    MaterialProvider = _ => new Material(Shader.Find("Standard")),
                    PrimaryTextureKey = "entity_test",
                    TextureWidth = geometry.TextureWidth,
                    TextureHeight = geometry.TextureHeight,
                    TargetHeight = 2f
                });
                Assert.That(built, Is.True);
                var body = root.transform.Find("Model/Bone_root/Bone_body");
                Assert.That(body, Is.Not.Null);
                Assert.That(body.localPosition, Is.EqualTo(new Vector3(0f, 0.25f, 0f)).Within(0.0001f));
                var renderers = root.GetComponentsInChildren<MeshRenderer>();
                Assert.That(renderers, Has.Length.GreaterThanOrEqualTo(2));
                foreach (var renderer in renderers)
                {
                    var mesh = renderer.GetComponent<MeshFilter>().sharedMesh;
                    Assert.That(mesh, Is.Not.Null);
                    Assert.That(mesh.uv.Length, Is.GreaterThan(0));
                    foreach (var uv in mesh.uv)
                    {
                        Assert.That(uv.x, Is.InRange(0f, 1f), renderer.name);
                        Assert.That(uv.y, Is.InRange(0f, 1f), renderer.name);
                    }
                }
                foreach (var renderer in renderers)
                {
                    var mesh = renderer.GetComponent<MeshFilter>().sharedMesh;
                    Assert.That(mesh.colors32.Length, Is.EqualTo(mesh.vertices.Length), renderer.name);
                    // vanilla-style per-face shading must be baked into vertex colors
                    Assert.That(mesh.colors32[0].r, Is.InRange(120, 255), renderer.name);
                }
                var shades = new System.Collections.Generic.HashSet<byte>();
                foreach (var renderer in renderers)
                    foreach (var color in renderer.GetComponent<MeshFilter>().sharedMesh.colors32) shades.Add(color.r);
                Assert.That(shades.Count, Is.GreaterThan(1), "multiple face shades are baked");
                var totalBounds = EncapsulateAll(renderers);
                Assert.That(totalBounds.size.y, Is.EqualTo(2f).Within(0.02f), "model is auto-scaled to the target height");
                Assert.That(totalBounds.min.y, Is.EqualTo(0f).Within(0.02f), "model bottom rests on the slot ground");
            }
            finally
            {
                Object.DestroyImmediate(root);
            }
        }

        [Test]
        public void BuilderMirrorsBedrockXAxisAndAppliesBaseY()
        {
            // asymmetric cube: origin [0,0,0], size [4,4,4] must land at x = -0.25..0 in Unity.
            var asymmetric = @"{
  ""format_version"": ""1.12.0"",
  ""minecraft:geometry"": [
    {
      ""description"": { ""identifier"": ""geometry.asymmetric"", ""texture_width"": 16, ""texture_height"": 16 },
      ""bones"": [
        { ""name"": ""body"", ""pivot"": [0, 0, 0], ""cubes"": [ { ""origin"": [0, 0, 0], ""size"": [4, 4, 4], ""uv"": [0, 0] } ] }
      ]
    }
  ]
}";
            var geometry = DemoMinecraftEntityGeometryParser.Parse(asymmetric);
            var root = new GameObject("EntityMirrorTestRoot");
            try
            {
                var built = DemoMinecraftEntityModelBuilder.TryBuild(root.transform, geometry, new DemoMinecraftEntityModelBuilder.BuildOptions
                {
                    MaterialProvider = _ => new Material(Shader.Find("Standard")),
                    PrimaryTextureKey = "entity_test",
                    TextureWidth = geometry.TextureWidth,
                    TextureHeight = geometry.TextureHeight,
                    BaseY = 0.5f
                });
                Assert.That(built, Is.True);
                var mesh = root.GetComponentInChildren<MeshFilter>().sharedMesh;
                var minX = mesh.vertices.Min(vertex => vertex.x);
                var maxX = mesh.vertices.Max(vertex => vertex.x);
                // Bedrock cube spans x 0..4; mirrored into Unity it spans -0.25..0.
                Assert.That(maxX, Is.EqualTo(0f).Within(0.0001f));
                Assert.That(minX, Is.EqualTo(-0.25f).Within(0.0001f));
                var bounds = EncapsulateAll(root.GetComponentsInChildren<MeshRenderer>());
                Assert.That(bounds.min.y, Is.EqualTo(0.5f).Within(0.01f), "BaseY lifts the model bottom to the hover height");
            }
            finally
            {
                Object.DestroyImmediate(root);
            }
        }

        [Test]
        public void BedrockBoneRotationInvertsXAndZSigns()
        {
            var rotation = DemoMinecraftEntityModelBuilder.ConvertBoneRotation(new[] { 90f, 0f, 0f });
            var expected = Quaternion.AngleAxis(-90f, Vector3.right);
            Assert.That(Quaternion.Angle(rotation, expected), Is.LessThan(0.1f));
        }

        [Test]
        public void FactoryMetadataCoversEveryEntityCard()
        {
            var entityCardIds = new[]
            {
                "pf_001", "pf_002", "tk_003", "tk_004", "pf_003", "pf_004", "cd_005", "tk_011",
                "pf_008", "si_002", "si_004", "cd_001", "cd_002", "nt_001", "tk_014", "nt_003",
                "si_003", "or_001", "or_002", "or_003", "or_004",
                "db_001", "db_003", "db_005", "db_008", "si_005", "cd_003", "or_005", "nt_002",
                "nt_004", "nt_005", "ed_001", "ed_003", "ed_004", "tk_015", "tk_017"
            };
            foreach (var cardId in entityCardIds)
            {
                Assert.That(DemoMinecraftModelFactory.TryGetTextureKey(cardId, out var textureKey), Is.True, cardId);
                Assert.That(textureKey, Does.StartWith("entity_"), cardId);
            }
            Assert.That(DemoMinecraftModelFactory.TryGetTextureKey("pf_005", out _), Is.False, "buildings are not entity models");
        }

        [Test]
        public void UnknownCardIdReportsUnsupportedModel()
        {
            var root = new GameObject("EntityUnsupportedRoot");
            try
            {
                Assert.That(DemoMinecraftModelFactory.TryBuild(
                    root.transform, "pf_005", true, _ => new Material(Shader.Find("Standard"))), Is.False);
            }
            finally
            {
                Object.DestroyImmediate(root);
            }
        }

        [TestCase("pf_001")]
        [TestCase("pf_002")]
        [TestCase("pf_003")]
        [TestCase("pf_004")]
        [TestCase("cd_005")]
        [TestCase("pf_008")]
        [TestCase("si_002")]
        [TestCase("si_004")]
        [TestCase("cd_001")]
        [TestCase("cd_002")]
        [TestCase("nt_001")]
        [TestCase("nt_003")]
        [TestCase("si_003")]
        [TestCase("or_001")]
        [TestCase("or_002")]
        [TestCase("or_003")]
        [TestCase("or_004")]
        [TestCase("db_001")]
        [TestCase("db_003")]
        [TestCase("db_005")]
        [TestCase("db_008")]
        [TestCase("si_005")]
        [TestCase("cd_003")]
        [TestCase("or_005")]
        [TestCase("nt_002")]
        [TestCase("nt_004")]
        [TestCase("nt_005")]
        [TestCase("ed_001")]
        [TestCase("ed_003")]
        [TestCase("ed_004")]
        [TestCase("tk_015")]
        [TestCase("tk_017")]
        public void ExtractedEntityModelsBuildWithValidGeometry(string cardId)
        {
            Assert.That(DemoMinecraftModelFactory.TryGetTextureKey(cardId, out var textureKey), Is.True);
            Assert.That(DemoMinecraftModelFactory.TryGetModelKey(cardId, out var modelKey), Is.True);
            if (Resources.Load<TextAsset>("DemoWorld/entity_models/" + modelKey) == null)
            {
                Assert.Ignore("Local entity geometry has not been extracted yet (run scripts/extract-minecraft-entity-models.ps1).");
            }

            var root = new GameObject("EntityIntegration_" + cardId);
            try
            {
                var built = DemoMinecraftModelFactory.TryBuild(
                    root.transform, cardId, player: true, key => new Material(Shader.Find("Standard")) { name = key });
                Assert.That(built, Is.True, cardId);
                var renderers = root.GetComponentsInChildren<MeshRenderer>();
                Assert.That(renderers, Has.Length.GreaterThanOrEqualTo(1), cardId);
                foreach (var renderer in renderers)
                {
                    var mesh = renderer.GetComponent<MeshFilter>().sharedMesh;
                    // Full cubes carry 6 faces (24 verts); zero-thickness slabs keep only coincident face pairs (16 or 8 verts).
                    Assert.That(mesh.vertices.Length, Is.InRange(8, 24), renderer.name);
                    Assert.That(mesh.vertices.Length % 4, Is.EqualTo(0), renderer.name);
                    Assert.That(mesh.uv.Length, Is.EqualTo(mesh.vertices.Length), renderer.name);
                    Assert.That(mesh.colors32.Length, Is.EqualTo(mesh.vertices.Length), renderer.name);
                    foreach (var uv in mesh.uv)
                    {
                        Assert.That(uv.x, Is.InRange(0f, 1f), $"{cardId}/{renderer.name}");
                        Assert.That(uv.y, Is.InRange(0f, 1f), $"{cardId}/{renderer.name}");
                    }
                }
                var bounds = EncapsulateAll(renderers);
                Assert.That(bounds.size.y, Is.GreaterThan(0.3f), cardId);
                Assert.That(bounds.size.x, Is.LessThan(5.5f), cardId);
                Assert.That(bounds.size.y, Is.LessThan(4.5f), cardId);
                Assert.That(bounds.size.z, Is.LessThan(4.5f), cardId);
                var animator = root.GetComponent<DemoEntityIdleAnimator>();
                if (animator != null) Assert.That(animator.TrackCount, Is.GreaterThan(0), cardId);
            }
            finally
            {
                Object.DestroyImmediate(root);
            }
        }

        [Test]
        public void BeeModelFlapsWingsWithIdleAnimator()
        {
            if (Resources.Load<TextAsset>("DemoWorld/entity_models/entity_bee") == null)
                Assert.Ignore("Local entity geometry has not been extracted yet.");
            var root = new GameObject("BeeIdleRoot");
            try
            {
                Assert.That(DemoMinecraftModelFactory.TryBuild(root.transform, "pf_001", true, key => new Material(Shader.Find("Standard"))), Is.True);
                var animator = root.GetComponent<DemoEntityIdleAnimator>();
                Assert.That(animator, Is.Not.Null, "bee attaches an idle animator");
                Assert.That(animator.TrackCount, Is.GreaterThanOrEqualTo(2), "both wings flap");
            }
            finally
            {
                Object.DestroyImmediate(root);
            }
        }

        [Test]
        public void StrayModelRendersHoodOverlayLayer()
        {
            if (Resources.Load<TextAsset>("DemoWorld/entity_models/entity_stray") == null ||
                Resources.Load<Texture2D>("DemoWorld/entity_stray_overlay") == null)
                Assert.Ignore("Local entity geometry or stray overlay texture has not been extracted yet.");
            var root = new GameObject("StrayOverlayRoot");
            try
            {
                Assert.That(DemoMinecraftModelFactory.TryBuild(root.transform, "si_003", true, key => new Material(Shader.Find("Standard")) { name = key }), Is.True);
                var overlayCubes = root.GetComponentsInChildren<Transform>(true);
                Assert.That(System.Linq.Enumerable.Any(overlayCubes, transform => transform.name == "Cube_entity_stray_overlay"),
                    Is.True, "hood overlay cubes are rendered on a second layer");
            }
            finally
            {
                Object.DestroyImmediate(root);
            }
        }

        [TestCase(true)]
        [TestCase(false)]
        public void PolarBearBindingPoseKeepsBodyHorizontalAndChildrenUpright(bool player)
        {
            Assert.That(Resources.Load<TextAsset>("DemoWorld/entity_models/entity_polar_bear"), Is.Not.Null,
                "this pose regression requires the registered Minecraft geometry");
            var root = new GameObject("PolarBearPose");
            var materials = new List<Material>();
            try
            {
                Assert.That(DemoMinecraftModelFactory.TryBuild(root.transform, "si_005", player, key =>
                {
                    var material = new Material(Shader.Find("Standard")) { name = key };
                    materials.Add(material);
                    return material;
                }), Is.True);
                var body = root.transform.Find("Model/Bone_body");
                Assert.That(body, Is.Not.Null);
                Assert.That(Quaternion.Angle(body.localRotation, Quaternion.identity), Is.LessThan(0.001f),
                    "binding pose must not rotate the animated body transform or its children");
                var cubes = body.GetComponentsInChildren<MeshFilter>().Where(value => value.transform.parent == body).ToArray();
                Assert.That(cubes.Length, Is.EqualTo(2));
                var bodyBounds = cubes[0].sharedMesh.bounds;
                bodyBounds.Encapsulate(cubes[1].sharedMesh.bounds);
                // Official legacy bind pose is +90 degrees about X. Its 26-pixel
                // body long axis becomes Z; the same cube UVs and 11-pixel thickness remain.
                Assert.That(bodyBounds.size.z, Is.EqualTo(26f / 16f).Within(0.0001f));
                Assert.That(bodyBounds.size.y, Is.EqualTo(11f / 16f).Within(0.0001f));
                Assert.That(Quaternion.Angle(root.transform.localRotation,
                    Quaternion.Euler(0, player ? 180f : 0, 0)), Is.LessThan(0.001f));
                foreach (var name in new[] { "head", "leg0", "leg1", "leg2", "leg3" })
                {
                    var bone = body.Find("Bone_" + name);
                    Assert.That(bone, Is.Not.Null);
                    Assert.That(Vector3.Dot(bone.up, Vector3.up), Is.GreaterThan(0.999f));
                }
                var bounds = EncapsulateAll(root.GetComponentsInChildren<MeshRenderer>());
                Assert.That(bounds.min.y, Is.EqualTo(0).Within(0.001f));
                Assert.That(bounds.size.y, Is.EqualTo(2f).Within(0.001f));
                var animator = root.GetComponent<DemoEntityIdleAnimator>();
                Assert.That(animator, Is.Not.Null);
                Assert.That(animator.TrackCount, Is.EqualTo(5));
                var originalMeshBounds = cubes[0].sharedMesh.bounds;
                // EditMode does not run MonoBehaviour message dispatch. Exercise
                // the actual update method directly at a deterministic idle phase.
                typeof(DemoEntityIdleAnimator).GetField("_time", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic)
                    .SetValue(animator, 0.2f);
                typeof(DemoEntityIdleAnimator).GetMethod("Update", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic)
                    .Invoke(animator, null);
                Assert.That(cubes[0].sharedMesh.bounds, Is.EqualTo(originalMeshBounds));
                Assert.That(Quaternion.Angle(body.localRotation, Quaternion.identity), Is.LessThan(0.001f));
                Assert.That(Quaternion.Angle(body.Find("Bone_head").localRotation, Quaternion.identity), Is.GreaterThan(0.01f),
                    "the corrected mesh must retain idle animation");
            }
            finally
            {
                Object.DestroyImmediate(root);
                foreach (var material in materials) Object.DestroyImmediate(material);
            }
        }

        [Test]
        public void EveryRegisteredEntitySelectsItsExactSourceGeometry()
        {
            var cardIds = DemoMinecraftModelFactory.GetRegisteredEntityCardIds();
            Assert.That(cardIds.Count, Is.EqualTo(36), "update the audit inventory when model registrations change");
            Assert.That(cardIds.Distinct().Count(), Is.EqualTo(cardIds.Count));
            foreach (var cardId in cardIds)
            {
                Assert.That(DemoMinecraftModelFactory.TryGetGeometryId(cardId, out var geometryId), Is.True);
                Assert.That(DemoMinecraftModelFactory.TryGetModelKey(cardId, out var modelKey), Is.True);
                var asset = Resources.Load<TextAsset>("DemoWorld/entity_models/" + modelKey);
                Assert.That(asset, Is.Not.Null, "registered local source missing: " + cardId);
                var selected = DemoMinecraftEntityGeometryParser.Parse(asset.text, geometryId);
                Assert.That(selected.Identifier, Is.EqualTo(geometryId), cardId);
                Assert.That(selected.Bones.Count, Is.GreaterThan(0), cardId);
            }
            Assert.That(DemoMinecraftModelFactory.TryGetGeometryId("pf_005", out var unsupported), Is.False);
            Assert.That(unsupported, Is.Null);
        }

        [Test]
        public void InvalidRegisteredGeometryCannotBuildAnotherModel()
        {
            var flags = System.Reflection.BindingFlags.Static | System.Reflection.BindingFlags.NonPublic;
            var registrations = (System.Collections.IDictionary)typeof(DemoMinecraftModelFactory)
                .GetField("Entities", flags).GetValue(null);
            var spec = registrations["pf_001"];
            var geometryField = spec.GetType().GetField("GeometryId");
            var originalId = geometryField.GetValue(spec);
            var root = new GameObject("InvalidGeometryRegistration");
            root.transform.localRotation = Quaternion.Euler(0, 40, 0);
            try
            {
                geometryField.SetValue(spec, "geometry.missing");
                UnityEngine.TestTools.LogAssert.Expect(LogType.Warning,
                    "Skipping entity model 'entity_bee': Requested geometry 'geometry.missing' was not found.");
                Assert.That(DemoMinecraftModelFactory.TryBuild(root.transform, "pf_001", true,
                    _ => throw new System.InvalidOperationException("invalid geometry must not resolve materials")), Is.False);
                Assert.That(root.transform.childCount, Is.EqualTo(0));
                Assert.That(Quaternion.Angle(root.transform.localRotation, Quaternion.Euler(0, 40, 0)), Is.LessThan(0.001f));
            }
            finally
            {
                geometryField.SetValue(spec, originalId);
                Object.DestroyImmediate(root);
            }
        }

        [TestCase("pf_002", true)]
        [TestCase("pf_002", false)]
        public void SheepBindingPoseAndWoolAtlasKeepLegsUpright(string cardId, bool player)
        {
            var root = new GameObject("SheepPose");
            var materials = new List<Material>();
            try
            {
                Assert.That(DemoMinecraftModelFactory.TryBuild(root.transform, cardId, player, key =>
                {
                    var material = new Material(Shader.Find("Standard")) { name = key };
                    materials.Add(material);
                    return material;
                }), Is.True);
                var body = root.transform.Find("Model/Bone_body");
                Assert.That(body, Is.Not.Null);
                Assert.That(Quaternion.Angle(body.localRotation, Quaternion.identity), Is.LessThan(0.001f));
                var baseCube = body.Find("Cube_entity_sheep").GetComponent<MeshFilter>().sharedMesh;
                Assert.That(baseCube.bounds.size.z, Is.EqualTo(16f / 16f).Within(0.0001f));
                Assert.That(baseCube.bounds.size.y, Is.EqualTo(6f / 16f).Within(0.0001f));
                foreach (var name in new[] { "leg0", "leg1", "leg2", "leg3" })
                    Assert.That(Vector3.Dot(body.Find("Bone_" + name).up, Vector3.up), Is.GreaterThan(0.999f));
                var wool = body.Find("Overlay_entity_sheep").GetComponent<MeshFilter>().sharedMesh;
                // Official Bedrock wool uses the lower half of the same 64x64 atlas.
                Assert.That(wool.uv.Min(value => value.y), Is.EqualTo(1f - 62f / 64f).Within(0.0001f));
                Assert.That(baseCube.uv.Min(value => value.y), Is.EqualTo(1f - 30f / 64f).Within(0.0001f));
                var head = root.transform.Find("Model/Bone_head");
                Assert.That(head.Find("Overlay_entity_sheep").GetComponent<MeshFilter>().sharedMesh.bounds.min.z,
                    Is.GreaterThan(head.Find("Cube_entity_sheep").GetComponent<MeshFilter>().sharedMesh.bounds.min.z));
                foreach (var name in new[] { "leg0", "leg1", "leg2", "leg3" })
                {
                    var leg = body.Find("Bone_" + name);
                    Assert.That(leg.Find("Overlay_entity_sheep").GetComponent<MeshFilter>().sharedMesh.bounds.min.y,
                        Is.GreaterThan(leg.Find("Cube_entity_sheep").GetComponent<MeshFilter>().sharedMesh.bounds.min.y));
                }
                Assert.That(Quaternion.Angle(root.transform.localRotation,
                    Quaternion.Euler(0, player ? 180f : 0, 0)), Is.LessThan(0.001f));
                Assert.That(EncapsulateAll(root.GetComponentsInChildren<MeshRenderer>()).min.y,
                    Is.EqualTo(0).Within(0.001f));
                var animator = root.GetComponent<DemoEntityIdleAnimator>();
                Assert.That(animator.TrackCount, Is.EqualTo(1));
                var flags = System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic;
                typeof(DemoEntityIdleAnimator).GetField("_time", flags).SetValue(animator, 0.2f);
                typeof(DemoEntityIdleAnimator).GetMethod("Update", flags).Invoke(animator, null);
                Assert.That(Vector3.Dot(body.Find("Bone_leg0").up, Vector3.up), Is.GreaterThan(0.999f));
                Assert.That(Quaternion.Angle(root.transform.Find("Model/Bone_head").localRotation,
                    Quaternion.identity), Is.GreaterThan(0.01f));
            }
            finally
            {
                Object.DestroyImmediate(root);
                foreach (var material in materials) Object.DestroyImmediate(material);
            }
        }

        [TestCase(true)]
        [TestCase(false)]
        public void BabySheepUsesDedicatedSourceProportionsAtlasAndRootSkeleton(bool player)
        {
            Assert.That(DemoMinecraftModelFactory.TryGetGeometryId("tk_003",out var id),Is.True);
            Assert.That(id,Is.EqualTo("geometry.sheep.baby"));
            Assert.That(DemoMinecraftModelFactory.TryGetTextureKey("tk_003",out var key),Is.True);
            Assert.That(key,Is.EqualTo("entity_sheep_baby"));
            Assert.That(DemoMinecraftModelFactory.TryGetOverlayGeometryId("tk_003",out _),Is.False);
            var root = new GameObject("OriginalBabySheep");
            var material = new Material(Shader.Find("Standard"));
            try
            {
                Assert.That(DemoMinecraftModelFactory.TryBuild(root.transform,"tk_003",player,_ => material),Is.True);
                Assert.That(root.GetComponentsInChildren<MeshRenderer>().Length,Is.EqualTo(6));
                Assert.That(root.GetComponentsInChildren<Transform>().Any(value=>value.name.StartsWith("Overlay_")),Is.False);
                var skeleton = root.transform.Find("Model/Bone_root");
                var head = skeleton.Find("Bone_head"); var body = skeleton.Find("Bone_body");
                Assert.That(head.localPosition,Is.EqualTo(new Vector3(0,8.5f,-2.5f)/16f));
                Assert.That(body.localPosition,Is.EqualTo(new Vector3(0,8,2.5f)/16f));
                Assert.That(head.GetComponentInChildren<MeshFilter>().sharedMesh.bounds.size,
                    Is.EqualTo(Vector3.one*5/16f));
                var bodyMesh = body.GetComponentInChildren<MeshFilter>().sharedMesh;
                Assert.That(bodyMesh.bounds.size,Is.EqualTo(new Vector3(6,4,9)/16f));
                Assert.That(bodyMesh.uv.Min(value=>value.y),Is.EqualTo(1f-23f/32f).Within(.000001f));
                foreach(var name in new[]{"leg0","leg1","leg2","leg3"})
                {
                    var leg=skeleton.Find("Bone_"+name);
                    Assert.That(Vector3.Distance(leg.GetComponentInChildren<MeshFilter>().sharedMesh.bounds.size,
                        new Vector3(2,5,2)/16f),Is.LessThan(.000001f));
                    Assert.That(Vector3.Dot(leg.up,Vector3.up),Is.GreaterThan(.999f));
                }
                var bounds=EncapsulateAll(root.GetComponentsInChildren<MeshRenderer>());
                Assert.That(bounds.size.y,Is.EqualTo(.9f).Within(.001f));
                Assert.That(bounds.min.y,Is.EqualTo(0).Within(.001f));
                Assert.That(root.transform.localScale,Is.EqualTo(Vector3.one));
                Assert.That(Quaternion.Angle(root.transform.localRotation,Quaternion.Euler(0,player?180:0,0)),Is.LessThan(.001f));
                var animator=root.GetComponent<DemoEntityIdleAnimator>();
                Assert.That(animator.TrackCount,Is.EqualTo(1));
                animator.SampleForAudit(.23f);
                Assert.That(Quaternion.Angle(head.localRotation,Quaternion.identity),Is.GreaterThan(.01f));
                Assert.That(Vector3.Dot(skeleton.Find("Bone_leg0").up,Vector3.up),Is.GreaterThan(.999f));
            }
            finally { Object.DestroyImmediate(root); Object.DestroyImmediate(material); }
        }

        [TestCase(0f)]
        [TestCase(180f)]
        [TestCase(35f)]
        public void BattlefieldIdleSwayPreservesRegisteredRootFacingWithoutAccumulation(float yaw)
        {
            var root = new GameObject("SwayRegression");
            var piece = new GameObject("Piece");
            piece.transform.SetParent(root.transform, false);
            piece.transform.localRotation = Quaternion.Euler(0, yaw, 0);
            piece.transform.localPosition = new Vector3(2, 1, 3);
            try
            {
                var battlefield = root.AddComponent<DemoBattlefield3D>();
                var flags = System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic;
                var floaterType = typeof(DemoBattlefield3D).GetNestedType("Floater", System.Reflection.BindingFlags.NonPublic);
                var floater = System.Activator.CreateInstance(floaterType, piece.transform, 1f, 0.9f);
                var floaters = (System.Collections.IList)typeof(DemoBattlefield3D).GetField("_floaters", flags).GetValue(battlefield);
                floaters.Add(floater);
                var update = typeof(DemoBattlefield3D).GetMethod("Update", flags);
                for (var index = 0; index < 30; index++) update.Invoke(battlefield, null);
                Assert.That(Quaternion.Angle(piece.transform.localRotation, Quaternion.Euler(0, yaw, 0)), Is.LessThanOrEqualTo(5.001f),
                    "idle sway must be relative to the registered facing, not reset or accumulated");
                Assert.That(piece.transform.localPosition.x, Is.EqualTo(2f));
                Assert.That(piece.transform.localPosition.z, Is.EqualTo(3f));
                Assert.That(piece.transform.localPosition.y, Is.InRange(0.944f, 1.056f));
            }
            finally { Object.DestroyImmediate(root); }
        }

        private static Bounds EncapsulateAll(IReadOnlyList<MeshRenderer> renderers)
        {
            var bounds = renderers[0].bounds;
            for (var index = 1; index < renderers.Count; index++) bounds.Encapsulate(renderers[index].bounds);
            return bounds;
        }
    }
}
