[CmdletBinding()]
param(
    [string]$Source = 'shared-schema\card-data\card-definition-registry.v1.json',
    [string]$Output = 'server-nakama\src\generated\card-catalog.ts',
    [switch]$Check
)

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
$sourcePath = Join-Path $repoRoot $Source
$outputPath = Join-Path $repoRoot $Output
$registry = Get-Content -LiteralPath $sourcePath -Raw -Encoding UTF8 | ConvertFrom-Json
$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('// Generated by scripts/sync-server-card-catalog.ps1. Do not edit by hand.')
$lines.Add('namespace BiomeRivalsRules {')
$lines.Add("  export const CARD_CATALOG_CONTENT_VERSION = $($registry.contentVersion);")
$lines.Add('  const CARD_DEFINITIONS: { [cardId: string]: CardRuleDefinition } = {')
for ($index = 0; $index -lt $registry.entries.Count; $index++) {
    $card = $registry.entries[$index]
    $comma = if ($index -lt $registry.entries.Count - 1) { ',' } else { '' }
    $effectIds = if ($card.effectIds.Count -gt 0) { "['" + (($card.effectIds | ForEach-Object { [string]$_ }) -join "', '") + "']" } else { '[]' }
    $keywords = if ($card.keywords.Count -gt 0) { "['" + (($card.keywords | ForEach-Object { [string]$_ }) -join "', '") + "']" } else { '[]' }
    $recipe = if ($card.craftingRecipe.Count -gt 0) { '[' + (($card.craftingRecipe | ForEach-Object { "{ cardId: '$($_.cardId)', count: $($_.count) }" }) -join ', ') + ']' } else { '[]' }
    $lines.Add("    '$($card.id)': { id: '$($card.id)', cardType: '$($card.cardType)', cost: $($card.cost), buildingSlots: $($card.buildingSlots), attack: $($card.attack), health: $($card.health), keywords: $keywords, hasCraftingRecipe: $($card.hasCraftingRecipe.ToString().ToLowerInvariant()), recipeId: '$($card.recipeId)', craftingRecipe: $recipe, craftedAttackBonus: $($card.craftedAttackBonus), craftedHealthBonus: $($card.craftedHealthBonus), craftedDurabilityBonus: $($card.craftedDurabilityBonus), effectImplementationStatus: '$($card.effectImplementationStatus)', effectIds: $effectIds }$comma")
}
$lines.Add('  };')
$lines.Add('')
$lines.Add('  export function getCardDefinition(cardId: string): CardRuleDefinition | null {')
$lines.Add('    return CARD_DEFINITIONS[cardId] || null;')
$lines.Add('  }')
$lines.Add('}')
$expected = [string]::Join([Environment]::NewLine, $lines) + [Environment]::NewLine
if ($Check) {
    if (-not (Test-Path -LiteralPath $outputPath)) { throw "Generated server card catalog is missing: $outputPath" }
    $actual = [System.IO.File]::ReadAllText($outputPath, [System.Text.Encoding]::UTF8)
    if ($actual -ne $expected) { throw 'Generated server card catalog is stale. Run scripts/sync-server-card-catalog.ps1.' }
    Write-Output "Server rule catalog is current with $($registry.entries.Count) cards."
}
else {
    [System.IO.Directory]::CreateDirectory((Split-Path -Parent $outputPath)) | Out-Null
    [System.IO.File]::WriteAllText($outputPath, $expected, [System.Text.UTF8Encoding]::new($false))
    Write-Output "Generated server rule catalog with $($registry.entries.Count) cards."
}
